---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: 3scale-deployment-git
  labels:
    app: 3scale-e2e-tests
spec:
  type: git
  params:
  - name: revision
    value: main
  - name: url
    value: https://github.com/gsaslis/3scale-deployment.git
